export const STATUS_LABEL: Record<string, string> = {
  new: "New to contact",
  undeliver: "Undeliver",
  wrong_number: "Wrong Number",
  wrong_lead: "Wrong Lead",
  wrong_service: "Wrong Service",
  wrong_person: "Wrong Person",
  already_got_someone: "Already Got Someone",
  service_provider_himself: "Service Provider Himself",
  converted: "Processed",
  need_follow_up: "Need Follow Up",
  called: "Called",
  messaged: "Messaged",
  follow_up: "Follow-up",
  interested: "Interested",
  not_interested: "Not interested",
  already_done: "Already done",
  no_response: "No response",
  closed_won: "Closed (done)",
  closed_lost: "Closed (lost)",
};

// Using explicit Tailwind colors to ensure classes are not purged at build time
export const STATUS_TONE: Record<string, string> = {
  new: "bg-[#e8dff5] text-[#7c6bb0] border-[#d9cfe4] shadow-sm",
  undeliver: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  wrong_number: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  wrong_lead: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  wrong_service: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  wrong_person: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  already_got_someone: "bg-[#efefec] text-[#74766B] border-[#d5d6cf] shadow-sm",
  service_provider_himself: "bg-[#efefec] text-[#74766B] border-[#d5d6cf] shadow-sm",
  converted: "bg-[#def7e8] text-[#07B053] border-[#a9dfbf] shadow-sm",
  need_follow_up: "bg-[#fff5d5] text-[#8f6a00] border-[#f1d27a] shadow-sm",
  called: "bg-[#e8dff5] text-[#7c6bb0] border-[#d9cfe4] shadow-sm",
  messaged: "bg-[#e8dff5] text-[#7c6bb0] border-[#d9cfe4] shadow-sm",
  follow_up: "bg-[#fff5d5] text-[#8f6a00] border-[#f1d27a] shadow-sm",
  interested: "bg-[#e8dff5] text-[#7c6bb0] border-[#d9cfe4] shadow-sm",
  not_interested: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  already_done: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
  closed_won: "bg-[#def7e8] text-[#07B053] border-[#a9dfbf] shadow-sm",
  closed_lost: "bg-[#f8e4e5] text-[#C1292E] border-[#e7b1b3] shadow-sm",
};
